import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { useRouter } from 'next/router';
import styled from 'styled-components';
import { DeviceMediaQueries } from 'common/device';

const Home: NextPage= () => {
  const router = useRouter();
  // router.push('/login')
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main style={{marginTop: "1rem"}}>
        {/* <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1> */}

        <Link href="/login">
          <a>Login</a>
        </Link>

        
      </Main>
      <p> 🚧 Web version under construction 🚧 </p>
    </div>
  )
}

export default Home

const Main = styled.main`
  @media ${DeviceMediaQueries.laptop} {
    display: none;
  }
`