import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import styled from 'styled-components';
import { DeviceMediaQueries } from 'common/device';

const Main = styled.main`
  @media ${DeviceMediaQueries.laptop} {
    display: none;
  }
`;

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main style={{ marginTop: '1rem' }}>
        <Link href="/login">Login</Link>
      </Main>
      <p> 🚧 Web version under construction 🚧 </p>
    </div>
  );
};

export default Home;
